name: Build docker image based on commit sha
permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, cicd]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Add IMAGE_TAG_SHORT_SHA env property with commit short sha
        run: echo "IMAGE_TAG_SHORT_SHA=aulaapp/aula-backend:$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: docker build -t $IMAGE_TAG_SHORT_SHA .

      - name: Push Docker image tag
        run: docker push $IMAGE_TAG_SHORT_SHA

      - name: '[legacy] Add IMAGE_TAG_LEGACY_SHORT_SHA env property with commit short sha'
        run: echo "IMAGE_TAG_LEGACY_SHORT_SHA=aulaapp/aula-backend:legacy-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: '[legacy] Build and tag legacy Docker image'
        run: docker build -f legacy/Dockerfile -t $IMAGE_TAG_LEGACY_SHORT_SHA

      - name: '[legacy] Push Docker legacy image tags'
        run: docker push $IMAGE_TAG_LEGACY_SHORT_SHA
