name: Release docker image based on release tag version and :latest
permissions:
  contents: read

on:
  release:
    types: [published]

env:
  IMAGE_TAG_LATEST: "${{ github.event.repository.name }}:latest"

jobs:
  sanitize_tag:
    runs-on: [self-hosted, cicd]
    steps:
      - name: Substitute illegal Docker image tag characters
        run: |
          echo "${{ github.event.release.tag_name }}" | \
            sed 's/[^a-zA-Z0-9_.-]/_/g' | \
            (echo -n "IMAGE_TAG_VERSION=${{ github.event.repository.name }}:" && cat) \
          >> $GITHUB_ENV
  build_v1:
    needs: sanitize_tag
    if: ${{ startsWith(github.event.release.tag_name, 'v1') }}
    runs-on: [self-hosted, cicd]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and tag Docker images
        working-directory: ./legacy
        run: docker build -t $IMAGE_TAG_VERSION .

      - name: Push Docker image tags
        run: docker push $IMAGE_TAG_VERSION
  build_v2:
    needs: sanitize_tag
    if: ${{ startsWith(github.event.release.tag_name, 'v2') }}
    runs-on: [self-hosted, cicd]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and tag Docker images
        run: docker build -t $IMAGE_TAG_VERSION -t $IMAGE_TAG_LATEST .

      - name: Push Docker image tags
        run: |
          docker push $IMAGE_TAG_VERSION && \
          docker push $IMAGE_TAG_LATEST
