name: Release docker image based on (1) commit sha (2) release tag version (3) :latest
permissions:
  contents: read

on:
  release:
    types: [published]

env:
  IMAGE_TAG_LATEST: "aulaapp/aula-backend:latest"
  IMAGE_TAG_VERSION: "aulaapp/aula-backend:${{ github.event.release.tag_name }}"

jobs:
  build_v1:
    if: ${{ startsWith(github.event.release.tag_name, 'v1') }}
    runs-on: [self-hosted, cicd]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and tag Docker images
        run: docker build -f legacy/Dockerfile -t $IMAGE_TAG_VERSION

      - name: Push Docker image tags
        run: docker push $IMAGE_TAG_VERSION
  build_v2:
    if: ${{ startsWith(github.event.release.tag_name, 'v2') }}
    runs-on: [self-hosted, cicd]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and tag Docker images
        run: docker build -f ./Dockerfile -t $IMAGE_TAG_VERSION -t $IMAGE_TAG_LATEST

      - name: Push Docker image tags
        run: |
          docker push $IMAGE_TAG_VERSION && \
          docker push $IMAGE_TAG_LATEST
